CREATE TABLE PRODUCT(
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(150) NOT NULL,
  provider_id VARCHAR (30) NOT NULL,
  url VARCHAR NOT NULL
)
CREATE TABLE PRICE(
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  price DECIMAL NOT NULL,
  timestamp TIMESTAMP WITHOUT TIMEZONE NOT NULL,
  product_id INT NOT NULL,
  FOREIGN KEY (product_id) REFERENCES PRODUCT(id)
)